FROM python:3.10.1-slim-buster

RUN apt update
RUN apt install ffmpeg libsm6 libxext6 -y


COPY requirements.txt /app/
RUN pip install -r /app/requirements.txt

COPY app/*.py /app/

COPY sample.json /


WORKDIR /app/

ENTRYPOINT ["python", "main.py"]

