FROM python:3.10.1-slim-buster

RUN apt update
RUN apt install ffmpeg libsm6 libxext6 -y


COPY streamingmodule/requirements.txt /app/
RUN pip install -r /app/requirements.txt

COPY streamingmodule/app/*.py /app/
COPY common app/common

COPY streamingmodule/sample.json /  


WORKDIR /app/

ENTRYPOINT ["python", "main.py"]

