# Generated by Django 3.0.8 on 2023-01-19 08:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('azure_parts', '0001_initial'),
        ('azure_cascades', '0001_initial'),
        ('azure_projects', '0001_initial'),
        ('inference_modules', '0001_initial'),
        ('cameras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDScenario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('inference_mode', models.CharField(choices=[('PD', 'part_detection'), ('PC', 'part_counting'), ('ES', 'employee_safety'), ('DD', 'defect_detection'), ('ESA', 'empty_shelf_alert'), ('TCC', 'total_customer_counting'), ('CQA', 'crowded_queue_alert')], default='PD', max_length=40)),
                ('fps', models.FloatField(default=0.0)),
                ('cameras', models.ManyToManyField(blank=True, to='cameras.Camera')),
                ('parts', models.ManyToManyField(blank=True, to='azure_parts.Part')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='azure_projects.Project')),
            ],
        ),
        migrations.CreateModel(
            name='PartDetection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('deployment_type', models.CharField(blank=True, max_length=200)),
                ('inference_mode', models.CharField(choices=[('PD', 'part_detection'), ('PC', 'part_counting'), ('ES', 'employee_safety'), ('DD', 'defect_detection'), ('ESA', 'empty_shelf_alert'), ('TCC', 'total_customer_counting'), ('CQA', 'crowded_queue_alert')], default='PD', max_length=40)),
                ('inference_protocol', models.CharField(choices=[('grpc', 'grpc'), ('http', 'http')], default='http', max_length=40)),
                ('inference_source', models.CharField(choices=[('lva', 'lva'), ('capture_module', 'capture_module')], default='lva', max_length=40)),
                ('needRetraining', models.BooleanField(default=True)),
                ('deployed', models.BooleanField(default=False)),
                ('deploy_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('has_configured', models.BooleanField(default=False)),
                ('accuracyRangeMin', models.IntegerField(default=30)),
                ('accuracyRangeMax', models.IntegerField(default=80)),
                ('maxImages', models.IntegerField(default=10)),
                ('metrics_is_send_iothub', models.BooleanField(default=False)),
                ('ava_is_send_iothub', models.BooleanField(default=False)),
                ('metrics_frame_per_minutes', models.IntegerField(default=6)),
                ('prob_threshold', models.IntegerField(default=60)),
                ('max_people', models.IntegerField(default=5)),
                ('counting_start_time', models.CharField(blank=True, max_length=200)),
                ('counting_end_time', models.CharField(blank=True, max_length=200)),
                ('fps', models.FloatField(default=10.0)),
                ('disable_video_feed', models.BooleanField(default=False)),
                ('cameras', models.ManyToManyField(blank=True, to='cameras.Camera')),
                ('cascade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='azure_cascades.Cascade')),
                ('inference_module', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inference_modules.InferenceModule')),
                ('parts', models.ManyToManyField(blank=True, to='azure_parts.Part')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='azure_projects.Project')),
            ],
        ),
    ]
