# Generated by Django 3.0.8 on 2023-01-19 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compute_devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('configure', models.CharField(blank=True, default='', max_length=2000, null=True)),
                ('tag_list', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('symphony_id', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('status', models.CharField(blank=True, default='', max_length=1000)),
                ('iothub_insights', models.CharField(blank=True, default='[]', max_length=100000)),
                ('compute_device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='compute_devices.ComputeDevice')),
            ],
        ),
    ]
