# Generated by Django 3.0.8 on 2022-08-10 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='status',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
