# Generated by Django 3.0.8 on 2022-06-21 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compute_devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computedevice',
            name='acceleration',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='computedevice',
            name='architecture',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='computedevice',
            name='iotedge_device',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='computedevice',
            name='iothub',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='computedevice',
            name='name',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='computedevice',
            name='tag_list',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
