# Generated by Django 3.0.8 on 2022-07-20 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compute_devices', '0002_auto_20220621_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='computedevice',
            name='solution_id',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='computedevice',
            name='symphony_id',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
