# Generated by Django 3.0.8 on 2022-08-01 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compute_devices', '0003_auto_20220720_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='computedevice',
            name='status',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
