# Generated by Django 3.0.8 on 2022-09-23 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compute_devices', '0004_computedevice_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='computedevice',
            name='cluster_type',
            field=models.CharField(blank=True, default='current', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='computedevice',
            name='is_k8s',
            field=models.BooleanField(default=False),
        ),
    ]
