apiVersion: apps/v1
kind: Deployment
metadata:
  name: kanportal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kanportal
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: kanportal
    spec:
      serviceAccountName: kan-user
      containers:
      - name: kanportal
        image: {{.Values.image.image}}:{{ .Values.image.tag | default .Chart.AppVersion }}
        imagePullPolicy: {{.Values.image.pullPolicy}}
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: 200m
        envFrom:
        - secretRef:
            name: azure-env
        env:          
          - name: DF_PD_VIDEO_SOURCE
            value: {{.Values.kanportal.videoSource}}
          - name: IS_K8S
            value: "true"
          - name: PORTAL_IP
            value: {{.Values.kanportal.portalIp}}
          - name: SYMPHONY_IP
            value: {{.Values.kanportal.symphonyIp}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqtt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mqtt
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: mqtt
    spec:
      serviceAccountName: kan-user
      containers:
      - name: mqtt
        image: "eclipse-mosquitto:2.0.11"
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 1883
        volumeMounts:
          - name: config
            mountPath: "/mosquitto/config/mosquitto.conf"
            subPath: "mosquitto.conf"
      volumes:
        - name: config
          configMap:
            name: mqtt-config
