{{- if not (eq .Values.service.type "LoadBalancer") }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kanportal
spec:
  ingressClassName: {{.Values.service.ingress}}
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kanportal
                port:
                  number: 8000
{{- end }}