---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: access-kan
rules:
  - apiGroups:
      [
        "",
        "networking.k8s.io",
        "fabric.kan",
        "solution.kan",
        "ai.kan",
        "config.kan",
      ]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kan-user
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kan-user
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: access-kan
subjects:
  - kind: ServiceAccount
    name: kan-user
    namespace: default
