apiVersion: v1
kind: Secret
metadata:
  name: azure-env
type: Opaque
data:
  TENANT_ID: {{.Values.servicePrincipal.tenantId  | b64enc | quote }}
  CLIENT_ID: {{.Values.servicePrincipal.clientId  | b64enc | quote }}
  CLIENT_SECRET: {{.Values.servicePrincipal.clientSecret  | b64enc | quote }}
  STORAGE_RESOURCE_GROUP: {{.Values.storage.storageResourceGroup  | b64enc | quote }}
  STORAGE_ACCOUNT: {{.Values.storage.storageAccount  | b64enc | quote }}
  STORAGE_CONTAINER: {{.Values.storage.storageContainer  | b64enc | quote }}
  SUBSCRIPTION_ID: {{.Values.storage.subscriptionId  | b64enc | quote }}
  KAN_AGENT_IMAGE: {{.Values.kanAgentImage  | b64enc | quote }}
  TRAINING_KEY: {{.Values.customvision.trainingKey  | b64enc | quote }}
  ENDPOINT: {{.Values.customvision.endpoint  | b64enc | quote }}
