# Generated by Django 3.0.8 on 2022-12-26 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azure_settings', '0003_auto_20220912_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='storage_resource_group',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
