# Generated by Django 3.0.8 on 2022-06-16 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azure_projects', '0013_project_is_trained'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='symphony_id',
            field=models.CharField(blank=True, default='', max_length=2000, null=True),
        ),
    ]
