# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

"""Project Application Insight configs.

If APP_INSIGHT_ON, django will run middleware that send
backend message to Application Insight
"""
import os

APPLICATIONINSIGHTS_TENANT_ID = ""
APPLICATIONINSIGHTS_CLIENT_ID = ""
APPLICATIONINSIGHTS_CLIENT_SECRET = ""

APPLICATIONINSIGHTS_TENANT_ID = os.environ.get(
    'APPLICATIONINSIGHTS_TENANT_ID', APPLICATIONINSIGHTS_TENANT_ID)
APPLICATIONINSIGHTS_CLIENT_ID = os.environ.get(
    'APPLICATIONINSIGHTS_CLIENT_ID', APPLICATIONINSIGHTS_CLIENT_ID)
APPLICATIONINSIGHTS_CLIENT_SECRET = os.environ.get(
    'APPLICATIONINSIGHTS_CLIENT_SECRET', APPLICATIONINSIGHTS_CLIENT_SECRET)

APP_INSIGHT_INST_KEY = ""
APP_INSIGHT_ENDPOINT = ""
APP_INSIGHT_INST_KEY = os.environ.get(
    'APPLICATIONINSIGHTS_INSTRUMENTATION_KEY', APP_INSIGHT_INST_KEY)
APP_INSIGHT_ENDPOINT = os.environ.get(
    'APPLICATIONINSIGHTS_INGESTION_ENDPOINT', APP_INSIGHT_ENDPOINT)
APP_INSIGHT_CONN_STR = f"InstrumentationKey={APP_INSIGHT_INST_KEY};IngestionEndpoint={APP_INSIGHT_ENDPOINT}"
