# Generated by Django 3.0.8 on 2023-01-19 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cascade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('flow', models.CharField(blank=True, default='', max_length=1000000, null=True)),
                ('raw_data', models.CharField(blank=True, default='', max_length=1000000, null=True)),
                ('screenshot', models.CharField(blank=True, default='', max_length=1000000, null=True)),
                ('tag_list', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('symphony_id', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('fps', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('acceleration', models.CharField(blank=True, default='', max_length=200, null=True)),
            ],
        ),
    ]
