# Generated by Django 3.0.8 on 2022-05-18 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azure_cascades', '0003_auto_20210827_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cascade',
            name='flow',
            field=models.CharField(blank=True, default='', max_length=1000000, null=True),
        ),
        migrations.AlterField(
            model_name='cascade',
            name='raw_data',
            field=models.CharField(blank=True, default='', max_length=1000000, null=True),
        ),
    ]
