# Generated by Django 3.0.8 on 2022-06-21 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azure_cascades', '0004_auto_20220518_0803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cascade',
            name='prediction_uri',
        ),
        migrations.AddField(
            model_name='cascade',
            name='tag_list',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
