# Generated by Django 3.0.8 on 2022-06-21 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azure_cascades', '0005_auto_20220621_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='cascade',
            name='symphony_id',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
