# Generated by Django 3.0.8 on 2022-08-01 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azure_cascades', '0007_cascade_fps'),
    ]

    operations = [
        migrations.AddField(
            model_name='cascade',
            name='acceleration',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
