# Generated by Django 3.0.8 on 2022-08-11 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0002_deployment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='iothub_insights',
            field=models.CharField(blank=True, default='[]', max_length=100000),
        ),
    ]
