FROM python:3.8-slim-buster

RUN apt update
RUN apt install ffmpeg libsm6 libxext6 -y


COPY predictmodule/requirements.txt /app/
RUN pip install -r /app/requirements.txt

COPY predictmodule/app/*.py /app/
COPY predictmodule/app/models/*.py /app/models/


WORKDIR /app/

CMD [ "python3", "main.py"]

