# Generated by Django 3.0.8 on 2022-05-18 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComputeDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('iothub', models.CharField(max_length=1000)),
                ('iotedge_device', models.CharField(max_length=1000)),
                ('architecture', models.CharField(max_length=1000)),
                ('acceleration', models.CharField(max_length=1000)),
                ('tag_list', models.CharField(max_length=1000)),
            ],
        ),
    ]
