# Generated by Django 3.0.8 on 2023-01-19 08:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('azure_settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customvision_id', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('download_uri', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('download_uri_fp16', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('download_uri_openvino', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('is_prediction_module', models.BooleanField(default=False)),
                ('prediction_uri', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('prediction_header', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('training_counter', models.IntegerField(default=0)),
                ('is_demo', models.BooleanField(default=False)),
                ('retraining_counter', models.IntegerField(default=0)),
                ('maxImages', models.IntegerField(default=20)),
                ('needRetraining', models.BooleanField(default=True)),
                ('relabel_expired_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('project_type', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('category', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('is_cascade', models.BooleanField(default=False)),
                ('type', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('node_type', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('inputs', models.CharField(blank=True, default='', max_length=2000, null=True)),
                ('outputs', models.CharField(blank=True, default='', max_length=2000, null=True)),
                ('combined', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('demultiply_count', models.IntegerField(blank=True, null=True)),
                ('openvino_library_name', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('openvino_model_name', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('classification_type', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('is_trained', models.BooleanField(default=False)),
                ('symphony_id', models.CharField(blank=True, default='', max_length=2000, null=True)),
                ('tag_list', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('setting', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='azure_settings.Setting')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=200)),
                ('log', models.CharField(max_length=1000)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='azure_projects.Project')),
            ],
        ),
    ]
