# Generated by Django 3.0.8 on 2022-06-21 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azure_projects', '0014_project_symphony_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='params',
        ),
        migrations.AddField(
            model_name='project',
            name='node_type',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
