# Generated by Django 3.0.8 on 2022-08-08 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azure_projects', '0015_auto_20220621_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tag_list',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
