# Default values for kan.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  pullPolicy: Always
  image: kanprod.azurecr.io/kanportal
  tag: ""
kanportal:
  videoSource: opencv
  portalIp: ""
  symphonyIp: ""
storage:
  storageResourceGroup: "customvision"
  storageAccount: "factoryai"
  storageContainer: "voe"
  subscriptionId: ""
customvision:
  endpoint: "https://southcentralus.api.cognitive.microsoft.com/"
  trainingKey: ""
servicePrincipal:
  tenantId: ""
  clientId: ""
  clientSecret: ""
symphonyAgentImage: "kanprod.azurecr.io/kan-agent"
symphonyAgentVersion: "0.41.44"
kanaiVersion: "0.45.2"
