# Default values for kan.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  pullPolicy: Always
  image: p4etest.azurecr.io/kanportal
  tag: ""
kanportal:
  videoSource: opencv
  portalIp: ""
  symphonyIp: ""
storage:
  storageResourceGroup: ""
  storageAccount: ""
  storageContainer: ""
  subscriptionId: ""
customvision:
  endpoint: ""
  trainingKey: ""
servicePrincipal:
  tenantId: ""
  clientId: ""
  clientSecret: ""
symphonyAgentImage: ""
symphonyAgentVersion: "0.41.44"
kanaiVersion: "0.45.2"
