import os

BLOB_STORAGE_CONNECTION_STRING = os.environ.get('BLOB_STORAGE_CONNECTION_STRING', '')
BLOB_STORAGE_CONTAINER = os.environ.get('BLOB_STORAGE_CONTAINER', 'voe')
WEBMODULE_URL = os.environ.get('WEBMODULE_URL', '')