# Generated by Django 3.0.8 on 2022-05-24 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0010_camera_media_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='tag_list',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
