# Generated by Django 3.0.8 on 2022-07-20 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0015_camera_is_live'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='snapshot',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
