# Generated by Django 3.0.8 on 2022-07-19 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azure_cascades', '0006_cascade_symphony_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cascade',
            name='fps',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
