# Default values for VisionOnEdge.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


runtime:
  accelerator: 
  storageSize: 5Gi
  stackEdge: false

azureIoT:
  hubConnectionString:
  edgeConnectionString:

customVision:
  endPoint:
  key:

nginxModule:
  port: 8181
  tolerations: []
  affinity: {}

webModule:
  tolerations: []
  affinity: {}

inferenceModule:
  cpuLimit: 
  tolerations: []
  affinity: {}

captureModule:
  tolerations: []
  affinity: {}

uploadModule:
  tolerations: []
  affinity: {}

predictModule:
  cpuLimit:
  numGPUs: 1
  tolerations: []
  affinity: {}

rtspsimModule:
  tolerations:
  affinity:
