# Default values for kan.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
kanAgentVersion: "0.41.38"
image:
  pullPolicy: Always
  image: p4etest.azurecr.io/kanportal
  tag:
kanportal:
  videoSource: opencv
storage:
  storageResourceGroup: ""
  storageAccount: ""
  storageContainer: ""
  subscriptionId: ""
customvision:
  endpoint: ""
  trainingKey: ""
servicePrincipal:
  tenantId: ""
  clientId: ""
  clientSecret: ""
