apiVersion: ai.symphony/v1
kind: Model
metadata:
  name: "face-detection"
spec:
  properties:
    displayName: "face-detection-retail-0004"
    model.type: "modelzoo"
    model.subtype: "intel.ObjectDetection"
    model.project: "face-detection-retail-0004"
    model.endpoint: ""
    model.version.1: ""
    model.symphony.id: "face-detection"
    tags: "['face']"
    state: trained
---
apiVersion: ai.symphony/v1
kind: Model
metadata:
  name: "emotion-recognition"
spec:
  properties:
    displayName: "emotions-recognition-retail-0003"
    model.type: "modelzoo"
    model.subtype: "intel.Classification"
    model.project: "emotions-recognition-retail-0003"
    model.endpoint: ""
    model.version.1: ""
    model.symphony.id: "emotion-recognition"
    tags: "['neutral', 'happy', 'sad', 'surprise', 'anger']"
    state: trained
---
apiVersion: ai.symphony/v1
kind: Model
metadata:
  name: "age-gender-recognition"
spec:
  properties:
    displayName: "age-gender-recognition-retail-0013"
    model.type: "modelzoo"
    model.subtype: "intel.Classification"
    model.project: "age-gender-recognition-retail-0013"
    model.endpoint: ""
    model.version.1: ""
    model.symphony.id: "age-gender-recognition"
    tags: "['female', 'male']"
    state: trained
---
apiVersion: ai.symphony/v1
kind: Model
metadata:
  name: "vehicle-attributes-recognition"
spec:
  properties:
    displayName: "vehicle-attributes-recognition-barrier-0039"
    model.type: "modelzoo"
    model.subtype: "intel.Classification"
    model.project: "vehicle-attributes-recognition-barrier-0039"
    model.endpoint: ""
    model.version.1: ""
    model.symphony.id: "vehicle-attributes-recognition"
    tags: "['white', 'gray', 'yellow', 'red', 'green', 'blue', 'black']"
    state: trained
---
apiVersion: ai.symphony/v1
kind: Model
metadata:
  name: "pedestrian-and-vehicle-detector"
spec:
  properties:
    displayName: "pedestrian-and-vehicle-detector-adas-0001"
    model.type: "modelzoo"
    model.subtype: "intel.ObjectDetection"
    model.project: "pedestrian-and-vehicle-detector-adas-0001"
    model.endpoint: ""
    model.version.1: ""
    model.symphony.id: "pedestrian-and-vehicle-detector"
    tags: "['vehicle', 'pedestrian']"
    state: trained
---
apiVersion: ai.symphony/v1
kind: Model
metadata:
  name: "person-detection"
spec:
  properties:
    displayName: "person-detection-retail-0013"
    model.type: "modelzoo"
    model.subtype: "intel.ObjectDetection"
    model.project: "person-detection-retail-0013"
    model.endpoint: ""
    model.version.1: ""
    model.symphony.id: "person-detection"
    tags: "['face']"
    state: trained
