---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: access-symphony 
rules:
- apiGroups: ["", "fabric.symphony","solution.symphony","ai.symphony","config.symphony"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: symphony-user
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: symphony-user
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: access-symphony
subjects:
- kind: ServiceAccount
  name: symphony-user
