apiVersion: v1
kind: Secret
metadata:
  name: azure-env
type: Opaque
data:
  TENANT_ID: {{.Values.servicePrincipal.tenantId  | b64enc }}
  CLIENT_ID: {{.Values.servicePrincipal.clientId  | b64enc }}
  CLIENT_SECRET: {{.Values.servicePrincipal.clientSecret  | b64enc }}
  STORAGE_ACCOUNT: {{.Values.storage.storageAccount  | b64enc }}
  STORAGE_CONTAINER: {{.Values.storage.storageContainer  | b64enc }}
  SUBSCRIPTION_ID: {{.Values.storage.subscriptionId  | b64enc }}
  SYMPHONY_AGENT_VERSION: {{.Values.symphonyAgentVersion  | b64enc }}
  TRAINING_KEY: {{.Values.customvision.trainingKey  | b64enc }}
  ENDPOINT: {{.Values.customvision.endpoint  | b64enc }}
