apiVersion: v1
kind: Service
metadata:
  name: symphonyportal
  labels:
    app: symphonyportal
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: symphonyportal
