# Generated by Django 3.0.8 on 2022-10-28 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_image_part_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='camera',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
