# Generated by Django 3.0.8 on 2023-01-19 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('azure_part_detections', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeployStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=200)),
                ('log', models.CharField(max_length=1000)),
                ('need_to_send_notification', models.BooleanField(default=False)),
                ('part_detection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='azure_part_detections.PartDetection')),
            ],
        ),
    ]
