# Generated by Django 3.0.8 on 2023-01-19 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cameras', '0001_initial'),
        ('azure_parts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CameraTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('send_video_to_cloud', models.BooleanField(default=False)),
                ('send_video_to_cloud_threshold', models.IntegerField(default=60)),
                ('recording_duration', models.IntegerField(default=1)),
                ('enable_tracking', models.BooleanField(default=False)),
                ('counting_start_time', models.CharField(blank=True, max_length=200)),
                ('counting_end_time', models.CharField(blank=True, max_length=200)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cameras.Camera')),
                ('parts', models.ManyToManyField(blank=True, to='azure_parts.Part')),
            ],
        ),
    ]
