# Generated by Django 3.0.8 on 2022-08-11 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azure_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='monitored_iothubs',
            field=models.CharField(blank=True, default='[]', max_length=1000),
        ),
    ]
