name: Release

on:
  workflow_dispatch:
permissions: write-all
env:
  CONTAINER_REGISTRY_NAME: "kanprod.azurecr.io"

jobs:
  build:
    if: github.repository == 'azure/kan' && github.actor == 'Haishi2016'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: increment version
        id: increment_version
        run: |
          version=$(cat .github/version/versions.txt)
          IFS='.' read -ra VERSION_PARTS <<< "$version"
          VERSION_PARTS[2]=$((VERSION_PARTS[2] + 1))
          new_version="${VERSION_PARTS[0]}.${VERSION_PARTS[1]}.${VERSION_PARTS[2]}"
          echo $new_version > .github/version/versions.txt
          echo "MODULE_VERSION=$new_version" >> $GITHUB_ENV

      - name: Build portal        
        run: |
          version=$(cat .github/version/versions.txt)
          echo $version > src/portal/modules/webmodule/version.txt
          echo "WEBMODULE_PATH=${GITHUB_WORKSPACE}/src/portal/modules/webmodule" >> $GITHUB_ENV
          cd src/portal
          echo CONTAINER_REGISTRY_NAME=${{ secrets.CONTAINER_REGISTRY_NAME }} > .env
          echo APPLICATIONINSIGHTS_INSTRUMENTATION_KEY=${{ secrets.APPLICATIONINSIGHTS_INSTRUMENTATION_KEY }} >> .env
          echo APPLICATIONINSIGHTS_INGESTION_ENDPOINT=${{ secrets.APPLICATIONINSIGHTS_INGESTION_ENDPOINT }} >> .env
          echo APPLICATIONINSIGHTS_TENANT_ID=${{ secrets.APPLICATIONINSIGHTS_TENANT_ID }} >> .env
          echo APPLICATIONINSIGHTS_CLIENT_ID=${{ secrets.APPLICATIONINSIGHTS_CLIENT_ID }} >> .env
          echo APPLICATIONINSIGHTS_CLIENT_SECRET=${{ secrets.APPLICATIONINSIGHTS_CLIENT_SECRET }} >> .env
          echo SECRET_KEY=${{ secrets.SECRET_KEY }} >> .env
          make build          
