# Generated by Django 3.0.8 on 2022-06-08 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0011_camera_tag_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='allowed_devices',
            field=models.CharField(blank=True, default='[]', max_length=1000),
        ),
        migrations.AddField(
            model_name='camera',
            name='password',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='camera',
            name='username',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
