# Generated by Django 3.0.8 on 2022-07-07 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0014_camera_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='is_live',
            field=models.BooleanField(default=True),
        ),
    ]
