# Generated by Django 3.0.8 on 2022-08-01 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0016_auto_20220720_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='status',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
